name: ai-hack
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cycler=0.12.1=py310haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py310h02ab6af_0
  - freetype=2.14.1=hfbffc0b_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=12.3.0=h3ef6528_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - joblib=1.5.3=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.22.1=hb237eb7_0
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h64815fc_1
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.8=py310haa95532_0
  - matplotlib-base=3.10.8=py310h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=2.2.5=py310h7894be3_2
  - numpy-base=2.2.5=py310h7794460_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py310h096bfcc_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pyparsing=3.2.5=py310haa95532_0
  - pyqt=6.9.1=py310h12ec796_0
  - pyqt6-sip=13.10.2=py310h630b2a1_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - qtbase=6.9.2=h3266e9d_6
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - scikit-learn=1.7.1=py310h3fbe716_0
  - scipy=1.15.3=py310h1bbe36f_1
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=80.10.2=py310haa95532_0
  - sip=6.12.0=py310h706e071_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - threadpoolctl=3.5.0=py310h4442805_1
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=py310haa95532_0
  - tornado=6.5.4=py310h02ab6af_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.20
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipykernel==7.2.0
      - ipython==8.38.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.6
      - platformdirs==4.7.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - pure-eval==0.2.3
      - pycparser==3.0
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pywinpty==3.0.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - send2trash==2.1.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - xgboost==3.2.0
prefix: C:\Users\Earth\anaconda3\envs\ai-hack
